on:
  workflow_dispatch:
    inputs:
      user_variable:
        description: "Enter a value to pass to Terraform"
        required: true
        type: number



jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      user_value: ${{ steps.set_output.outputs.variable_value }}
    steps:
      - name: Capture User Input
        id: set_output
        run: | 
          echo ${{ github.event.inputs.user_variable }}
          echo "::set-output name=variable_value::${{ github.event.inputs.user_variable }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Retained Value in Another Job
        env:
          RETAINED_VALUE: ${{ needs.job1.outputs.user_value }}
        run: |
          echo "The retained value is: $RETAINED_VALUE"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform configuration
        run: terraform plan

