on:
  workflow_dispatch:
    inputs:
      user_variable:
        description: "Enter a value to pass to Terraform"
        required: true
        type: number

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      user_value: ${{ steps.set_output.outputs.variable_value }}
    steps:
      - name: Capture User Input
        env:
          TF_VAR_user_variable: ${{ inputs.user_variable }}
        id: set_output
        run: | 
          echo ${{ github.event.inputs.user_variable }}
          echo "::set-output name=variable_value::${{ github.event.inputs.user_variable }}"
          echo ${{ inputs.user_variable }}
          echo TF_VAR_user_variable
          echo "user_variable = \"${TF_VAR_user_variable}\"" > tfvars/dev.tfvars


  job2:
    needs: [ job1 ]
    uses: AnjuBhole/spring-mocroservices/.github/workflows/reusable-wf.yml@main
    secrets: inherit




