on:
  workflow_dispatch:
    inputs:
      user_variable:
        description: "Enter a value to pass to Terraform"
        required: true
        type: number



jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      user_value: ${{ steps.set_output.outputs.variable_value }}
    steps:
      - name: Capture User Input
        id: set_output
        run: | 
          echo ${{ github.event.inputs.user_variable }}
          echo "::set-output name=variable_value::${{ github.event.inputs.user_variable }}"

  job2:
    ci:
      name: reuse
      needs: [ job1 ]
      uses: AnjuBhole/spring-mocroservices/.github/workflows/reusable-wf.yml@main




