on:
  workflow_dispatch:
    inputs:
      user_variable:
        description: "Enter a value to pass to Terraform"
        required: true
        type: number

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Capture User Input
        env:
          TF_VAR_user_variable: ${{ inputs.user_variable }}
        id: set_output
        run: | 
          echo ${{ inputs.user_variable }}

  job2:
    needs: [ job1 ]
    uses: AnjuBhole/spring-mocroservices/.github/workflows/reusable-wf.yml@main
    secrets: inherit




